# CMake generated Testfile for 
# Source directory: /home/theunknownthing/RCompiler
# Build directory: /home/theunknownthing/RCompiler/build_new
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unit_preprocessor "/home/theunknownthing/RCompiler/build_new/unit_preprocessor")
set_tests_properties(unit_preprocessor PROPERTIES  LABELS "preprocessor;stable" WORKING_DIRECTORY "/home/theunknownthing/RCompiler/tests/unit" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;36;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_simple_tests "/home/theunknownthing/RCompiler/build_new/parser_simple_tests")
set_tests_properties(parser_simple_tests PROPERTIES  LABELS "parser;legacy" WORKING_DIRECTORY "/home/theunknownthing/RCompiler" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;42;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_basic "/home/theunknownthing/RCompiler/build_new/parser_basic")
set_tests_properties(parser_basic PROPERTIES  LABELS "parser;basic;stable" WORKING_DIRECTORY "/home/theunknownthing/RCompiler" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;47;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_comprehensive "/home/theunknownthing/RCompiler/build_new/parser_comprehensive")
set_tests_properties(parser_comprehensive PROPERTIES  LABELS "parser;comprehensive;unstable" WORKING_DIRECTORY "/home/theunknownthing/RCompiler" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;52;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_arithmetic_control "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/arithmetic_control.rs" "/home/theunknownthing/RCompiler/examples/lexer/arithmetic_control.tokens")
set_tests_properties(lexer_arithmetic_control PROPERTIES  LABELS "lexer;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_char_literals "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/char_literals.rs" "/home/theunknownthing/RCompiler/examples/lexer/char_literals.tokens")
set_tests_properties(lexer_char_literals PROPERTIES  LABELS "lexer;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_empty "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/empty.rs" "/home/theunknownthing/RCompiler/examples/lexer/empty.tokens")
set_tests_properties(lexer_empty PROPERTIES  LABELS "lexer;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_greedy_operators "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/greedy_operators.rs" "/home/theunknownthing/RCompiler/examples/lexer/greedy_operators.tokens")
set_tests_properties(lexer_greedy_operators PROPERTIES  LABELS "lexer;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_integer_followed_by_identifier "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/integer_followed_by_identifier.rs" "/home/theunknownthing/RCompiler/examples/lexer/integer_followed_by_identifier.tokens")
set_tests_properties(lexer_integer_followed_by_identifier PROPERTIES  LABELS "lexer;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_integers_underscores "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/integers_underscores.rs" "/home/theunknownthing/RCompiler/examples/lexer/integers_underscores.tokens")
set_tests_properties(lexer_integers_underscores PROPERTIES  LABELS "lexer;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_invalid_symbols "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/invalid_symbols.rs" "/home/theunknownthing/RCompiler/examples/lexer/invalid_symbols.tokens")
set_tests_properties(lexer_invalid_symbols PROPERTIES  LABELS "lexer;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_keywords_self "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/keywords_self.rs" "/home/theunknownthing/RCompiler/examples/lexer/keywords_self.tokens")
set_tests_properties(lexer_keywords_self PROPERTIES  LABELS "lexer;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_no_whitespace "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/no_whitespace.rs" "/home/theunknownthing/RCompiler/examples/lexer/no_whitespace.tokens")
set_tests_properties(lexer_no_whitespace PROPERTIES  LABELS "lexer;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_path_fatarrow "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/path_fatarrow.rs" "/home/theunknownthing/RCompiler/examples/lexer/path_fatarrow.tokens")
set_tests_properties(lexer_path_fatarrow PROPERTIES  LABELS "lexer;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_simple_function "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/simple_function.rs" "/home/theunknownthing/RCompiler/examples/lexer/simple_function.tokens")
set_tests_properties(lexer_simple_function PROPERTIES  LABELS "lexer;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_string_escaped "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/string_escaped.rs" "/home/theunknownthing/RCompiler/examples/lexer/string_escaped.tokens")
set_tests_properties(lexer_string_escaped PROPERTIES  LABELS "lexer;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_unterminated_string "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/unterminated_string.rs" "/home/theunknownthing/RCompiler/examples/lexer/unterminated_string.tokens")
set_tests_properties(lexer_unterminated_string PROPERTIES  LABELS "lexer;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(lexer_whitespace_only "/home/theunknownthing/RCompiler/build_new/lexer_case_runner" "/home/theunknownthing/RCompiler/examples/lexer/whitespace_only.rs" "/home/theunknownthing/RCompiler/examples/lexer/whitespace_only.tokens")
set_tests_properties(lexer_whitespace_only PROPERTIES  LABELS "lexer;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;69;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_0 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/0.rs")
set_tests_properties(parser_ast_0 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_1 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/1.rs")
set_tests_properties(parser_ast_1 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_10 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/10.rs")
set_tests_properties(parser_ast_10 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_11 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/11.rs")
set_tests_properties(parser_ast_11 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_12 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/12.rs")
set_tests_properties(parser_ast_12 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_13 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/13.rs")
set_tests_properties(parser_ast_13 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_14 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/14.rs")
set_tests_properties(parser_ast_14 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_15 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/15.rs")
set_tests_properties(parser_ast_15 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_16 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/16.rs")
set_tests_properties(parser_ast_16 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_17 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/17.rs")
set_tests_properties(parser_ast_17 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_18 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/18.rs")
set_tests_properties(parser_ast_18 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_19 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/19.rs")
set_tests_properties(parser_ast_19 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_2 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/2.rs")
set_tests_properties(parser_ast_2 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_20 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/20.rs")
set_tests_properties(parser_ast_20 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_21 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/21.rs")
set_tests_properties(parser_ast_21 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_22 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/22.rs")
set_tests_properties(parser_ast_22 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_23 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/23.rs")
set_tests_properties(parser_ast_23 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_24 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/24.rs")
set_tests_properties(parser_ast_24 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_25 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/25.rs")
set_tests_properties(parser_ast_25 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_26 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/26.rs")
set_tests_properties(parser_ast_26 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_3 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/3.rs")
set_tests_properties(parser_ast_3 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_4 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/4.rs")
set_tests_properties(parser_ast_4 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_5 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/5.rs")
set_tests_properties(parser_ast_5 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_6 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/6.rs")
set_tests_properties(parser_ast_6 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_7 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/7.rs")
set_tests_properties(parser_ast_7 PROPERTIES  LABELS "parser;stable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_8 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/8.rs")
set_tests_properties(parser_ast_8 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(parser_ast_9 "/home/theunknownthing/RCompiler/build_new/parser_smoke_runner" "/home/theunknownthing/RCompiler/examples/ast/9.rs")
set_tests_properties(parser_ast_9 PROPERTIES  LABELS "parser;unstable" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;87;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
add_test(integration_lexer_with_preprocessor "/home/theunknownthing/RCompiler/build_new/integration_lexer_with_preprocessor")
set_tests_properties(integration_lexer_with_preprocessor PROPERTIES  LABELS "integration;stable" WORKING_DIRECTORY "/home/theunknownthing/RCompiler/tests/integration" _BACKTRACE_TRIPLES "/home/theunknownthing/RCompiler/CMakeLists.txt;101;add_test;/home/theunknownthing/RCompiler/CMakeLists.txt;0;")
