name: Component Test Template

on:
  workflow_call:
    inputs:
      component:
        description: "Component identifier (preprocessor, lexer, parser)"
        required: true
        type: string
      test_label:
        description: "CTest label associated with the component"
        required: true
        type: string
      build_type:
        description: "CMake build type"
        required: false
        default: Release
        type: string
      build_dir:
        description: "CMake build directory"
        required: false
        default: ""
        type: string
      build_target:
        description: "Specific target to build before running tests"
        required: false
        default: ""
        type: string
      post_build_command:
        description: "Optional shell commands to run after building"
        required: false
        default: ""
        type: string
      test_command:
        description: "Custom shell commands to execute tests"
        required: false
        default: ""
        type: string

jobs:
  run-component-tests:
    name: "${{ inputs.component }} (${{ matrix.compiler }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    env:
      BUILD_DIR: ${{ inputs.build_dir != '' && inputs.build_dir || format('build/{0}-{1}', matrix.compiler, inputs.component) }}
      BUILD_TYPE: ${{ inputs.build_type }}
      CMAKE_GENERATOR: Ninja
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build ${{ matrix.compiler }}

      - name: Cache CMake configuration and objects
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.BUILD_DIR }}
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ inputs.component }}-${{ hashFiles('CMakeLists.txt', 'src/**/*.cpp', 'src/**/*.hpp', 'include/**/*.hpp', 'tests/ci_*.cpp', 'ci/files/**/*', 'ci/files_expected/**/*', 'scripts/semantic_benchmark', 'testcases/**/*') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.compiler }}-${{ inputs.component }}-

      - name: Configure CMake
        run: |
          cmake -S . -B "$BUILD_DIR" -G "$CMAKE_GENERATOR" \
                -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
                -DBUILD_TESTING=ON \
                -DCMAKE_CXX_COMPILER=${{ matrix.compiler == 'clang' && 'clang++' || 'g++' }}

      - name: Build component tests
        run: |
          set -e
          TARGET="${{ inputs.build_target }}"
          if [ -z "$TARGET" ]; then
            TARGET="ci_${{ inputs.component }}_tests"
          fi
          cmake --build "$BUILD_DIR" --target "$TARGET" --parallel

      - name: Post-build hook
        if: ${{ inputs.post_build_command != '' }}
        run: |
          set -e
          printf '%s\n' "${{ inputs.post_build_command }}" > /tmp/post-build.sh
          chmod +x /tmp/post-build.sh
          /tmp/post-build.sh

      - name: Run component test suite
        env:
          TEST_COMMAND: ${{ inputs.test_command }}
        run: |
          set -e
          if [ -z "$TEST_COMMAND" ]; then
            ctest --test-dir "$BUILD_DIR" --output-on-failure -L ${{ inputs.test_label }}
          else
            {
              printf '%s\n' '#!/usr/bin/env bash'
              printf '%s\n' "$TEST_COMMAND"
            } > /tmp/run-tests.sh
            chmod +x /tmp/run-tests.sh
            bash /tmp/run-tests.sh
          fi

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.component }}-${{ matrix.compiler }}-logs
          path: |
            ${{ env.BUILD_DIR }}/Testing/Temporary/LastTest.log
            ${{ env.BUILD_DIR }}/*.log
          if-no-files-found: ignore
