name: Lexer CI

on:
  push:
    branches: [ main, fix-ci ]
  pull_request:
    branches: [ main, fix-ci ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lexer:
    uses: ./.github/workflows/component-template.yml
    with:
      component: lexer
      test_label: lexer
    secrets: inherit
