name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Create archive
        run: |
          tar -czf rcompiler-${{ github.ref_name }}-linux-x86_64.tar.gz -C build rcompiler

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rcompiler-${{ github.ref_name }}-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
