#pragma once

#include <cctype>
#include <iostream>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace rc {

// --- GENERATED By Google Gemini ---
#define X(name, str) name,
enum class TokenType {
#include "token_defs.def"
};
#undef X

const char *toString(TokenType type);

std::ostream &operator<<(std::ostream &os, const TokenType &type);

// --- END GENERATED By Google Gemini ---

extern const std::unordered_map<std::string_view, TokenType>
    keywordToTokenType;

extern const std::unordered_map<std::string_view, TokenType>
    operatorToTokenType;

extern const std::unordered_map<std::string_view, TokenType>
    punctuationToTokenType;

struct Token {
  TokenType type;
  std::string lexeme;
};

class Lexer {
public:
  Lexer(const std::string &source);
  std::vector<Token> tokenize();

private:
  std::string source;
  std::vector<Token> tokens;

  void firstPass();
  bool checkWordBoundary(char c);
  bool isPunctuation(char c);
  void checkForKeywords();
};







} // namespace rc
